# DESCRIPTION: Travis-CI config
#
# Copyright 2003-2019 by Todd Strader. Verilator is free software; you can
# redistribute it and/or modify it under the terms of either the GNU Lesser
# General Public License Version 3 or the Perl Artistic License Version 2.0.

version: ~> 1.0

os: linux
language: cpp
cache: ccache

env:
  global:
    - VERILATOR_CACHE=$HOME/verilator_cache
    - VERILATOR_ROOT=$PWD/submodules/verilator
    - VERILATOR_NUM_JOBS=$(echo `nproc` + 1 | bc)
    - OBJCACHE=ccache

cache:
  directories:
    - $VERILATOR_CACHE

before_install:
  - ci/update_submodules.sh

before_script:
  - export NUM_JOBS=$((`nproc` + 1))
  - export DRIVER_FLAGS="--j $NUM_JOBS"
  - $VERILATOR_ROOT/ci/build_verilator.sh

stages:
  - build
  - test

jobs:
  include:
# build_verilator.sh will only build for this stage, all other stages
#   must have a cached copy of the tool
    - stage: build
      name: Build Verilator
      script: echo "Done building Verilator"
    - stage: test
      name: Run Tests
      script: make test

after_script:
  - git submodule status

notifications:
  email:
    if: repo = verilator/verilator_ext_tests
    recipients:
      - todd.strader@gmail.com
